# Generated by Django 5.0.7 on 2024-08-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="records",
            name="contract",
            field=models.FileField(blank=True, null=True, upload_to="contracts/"),
        ),
    ]
