# Generated by Django 5.0.7 on 2024-08-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_records_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("outcome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="website.records",
                    ),
                ),
            ],
        ),
    ]
